// Code generated by "stringer -type ErrCode -linecomment"; DO NOT EDIT.

package errcode

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Success-0]
	_ = x[ServerError-10001]
	_ = x[ParamsError-10002]
	_ = x[TokenAuthFail-10003]
	_ = x[TokenIsNotExist-10004]
}

const (
	_ErrCode_name_0 = "success"
	_ErrCode_name_1 = "服务内部错误参数信息有误Token鉴权失败Token不存在"
)

var (
	_ErrCode_index_1 = [...]uint8{0, 18, 36, 53, 67}
)

func (i ErrCode) String() string {
	switch {
	case i == 0:
		return _ErrCode_name_0
	case 10001 <= i && i <= 10004:
		i -= 10001
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
